#!/usr/bin/env bash
set -e

clone-or-pull () {
    dir=$(python -c "
print('$2' or '$1'.rsplit('.git', 1)[0].split('/')[-1])
")
    if [[ -d $dir ]]
    then
        echo "Pulling $dir"
        cd $dir
        git pull
        cd ..
    else
        echo "Cloning $dir"
        git clone $1 $2
    fi
}

ln -sf ~/miniconda3 ~/anaconda
mkdir -p ~/Documents/gists/

cd ~/Documents
clone-or-pull git@github.com:git/git.git
cd ~/Documents/git/contrib/diff-highlight/
make
cd ~/Documents

clone-or-pull git@github.com:ipython/ipython.git
# clone-or-pull git://git.sv.gnu.org/emacs.git
clone-or-pull git@github.com:inducer/pudb.git

# Needed in .emacs:
# TODO: byte compile some stuff
# clone-or-pull git://git.sv.gnu.org/auctex.git
# cd auctex
# ./autogen.sh

clone-or-pull git@github.com:dacap/keyfreq.git
clone-or-pull git@github.com:nonsequitur/smex.git
# Until https://github.com/nonsequitur/smex/pull/12 is merged
cd smex
# ignore remote already exists.
git remote add haxney git@github.com:haxney/smex.git || true
git fetch haxney
git checkout customize
git branch --set-upstream-to=haxney/customize customize
cd ~/Documents/

clone-or-pull git@github.com:fgallina/python.el.git
# clone-or-pull git@gitlab.com:python-mode-devs/python-mode.git
cd python.el
# ignore remote already exists
git remote add github git@github.com:asmeurer/python.el.git || true
git fetch github
git checkout indentation
# ignore remote
git branch --set-upstream-to=github/indentation indentation
cd ~/Documents/
clone-or-pull git@github.com:purcell/mmm-mode.git
# TODO: doctest-mode
clone-or-pull git@github.com:tkf/emacs-jedi.git
cd emacs-jedi
echo "Creating conda environment for jedi"
conda install -p env jedi epc
cd ~/Documents/
clone-or-pull git@github.com:juergenhoetzel/profile-dotemacs.git

clone-or-pull git@github.com:asmeurer/mypython
mkdir -p ~/bin/
ln -s -f ~/Documents/mypython/bin/mypython ~/bin/mypython

if [[ $(uname) != "Darwin" ]]; then
    clone-or-pull git@github.com:jcs/xbanish.git
    cd xbanish
    make
    cd ~/Documents/
fi

CONDA_PKGS="--file=$HOME/Documents/mypython/requirements.txt argcomplete hunspell-en pyflakes mpmath ipython conda-build xonsh hub bash matplotlib pyinstrument pytest sympy pudb setproctitle mamba jedi-language-server esbonio pipx"

if [[ $(uname) == "Darwin" ]]; then
    # conda-forge emacs package is broken on linux
    CONDA_PKGS="$CONDA_PKGS prefsync"
    conda create -n emacs emacs nodejs hunspell-en pyflakes ruff
else
    conda create -n emacs nodejs hunspell-en pyflakes
fi
conda update --all -n emacs

pixi global install bash fd-find asitop dust duf ripgrep
if [[ $(uname) == "Darwin" ]]; then
    pixi glocal install proc
fi
pixi global install hunspell --with hunspell-en
pixi global install --environment emacs emacs --with nodejs --with hunspell-en --with pyflakes --with ruff
pixi global update

conda install $CONDA_PKGS
pipx install shell-gpt
pipx upgrade-all

# Install a larger English dictionary for hunspell/Emacs.
#
# The conda/pixi hunspell-en package ships the standard en_US dictionary
# (~50k base words), which misses a lot of real English vocabulary. This is a
# SCOWL (Spell Checker Oriented Word Lists) build at size 95 (~150k base
# words), generated by the official tool at http://app.aspell.net/create. It's
# the same upstream the standard dictionary comes from, just much larger, and
# it still rejects ordinary typos.
#
# It is installed outside this repo (in ~/.local/share/hunspell) rather than
# committed here. The basename stays "en_US" so the personal word list
# ~/.hunspell_en_US still auto-loads. .emacs points hunspell at it via an
# absolute -d path; see the ispell-local-dictionary-alist there.
HUNSPELL_DICT_DIR="$HOME/.local/share/hunspell"
mkdir -p "$HUNSPELL_DICT_DIR"
echo "Downloading SCOWL size-95 en_US hunspell dictionary"
SCOWL_TMP=$(mktemp -d)
curl -fsSL "http://app.aspell.net/create?max_size=95&spelling=US&max_variant=3&diacritic=both&special=hacker&encoding=utf-8&format=inline&download=hunspell" -o "$SCOWL_TMP/scowl.zip"
unzip -o -q "$SCOWL_TMP/scowl.zip" -d "$SCOWL_TMP"
cp "$SCOWL_TMP/en_US-custom.dic" "$HUNSPELL_DICT_DIR/en_US.dic"
cp "$SCOWL_TMP/en_US-custom.aff" "$HUNSPELL_DICT_DIR/en_US.aff"
rm -rf "$SCOWL_TMP"

clone-or-pull git@github.com:jwiegley/use-package.git
cd ~/Documents/use-package
make elc
cd ~/Documents

activate-global-python-argcomplete --user

# echo "Running prefsync"
# prefsync ~/Library/Preferences/org.pqrs.Karabiner.plist ~/Documents/dotfiles/Library/Preferences/org.pqrs.Karabiner.plist
